### ISSUE TITLE
The readme instructions on using precommit throws an error

### ISSUE THREAD

**Issue by timrooke1991** [rkotze/git-mob#102]
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob issues]
- [x] Tried upgrading to the latest git-mob version (`npm i -g git-mob`)
- [x] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob issues]: https://github.com/rkotze/git-mob/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

- Following the readme instructions to use `precommit` and `git-mob` together throws an error

**The example posted in the read me**

```
// .pre-commit-config.yaml
repos:
  - repo: https://github.com/rkotze/git-mob
    rev: { tag-version }
    hooks:
      - id: add-coauthors
        stages: ["prepare-commit-msg"]
```

**Output**: Throws the CLI error - because use of `tag-version` is not compatible
```
An error has occurred: InvalidConfigError:
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/rkotze/git-mob')
==> At key: rev
=====> Expected string got dict
Check the log at /Users/timrooke/.cache/pre-commit/pre-commit.log
```

**If I solve this issue by pinning the version:**

```
// .pre-commit-config.yaml
repos:
  - repo: https://github.com/rkotze/git-mob
    rev: v2.3.5
    hooks:
      - id: add-coauthors
        stages: ["prepare-commit-msg"]
```

**Output:** Throws the CLI error - because `.pre-commit-hooks.yaml` is not at the root level of the `git-mob` report
```
An error has occurred: InvalidManifestError:
=====> /Users/me/.cache/pre-commit/repoycrmzqj6/.pre-commit-hooks.yaml is not a file
Check the log at /Users/me/.cache/pre-commit/pre-commit.log
```

### Steps to Reproduce

1. `brew install pre-commit`
2. Add a `.pre-commit-config.yaml` with one of the above configurations 
3. Run `pre-commit autoupdate` (you may see the error in the CLI at this point)
4. `git add . && git commit -m "Add some files"`
5. The pre-commit hook errors as above

**Expected behavior:** [What you expect to happen]
- Pre-commit hook to pass and append any git-mob users to the commit

**Actual behavior:** [What actually happens]
- The pre-commit hook errors as above

**Reproduces how often:** [What percentage of the time does it reproduce?]
- Every time

### Versions

- operating system and version: Mac (Apple Silicone); Monterey v12.6.2
- git version 2.37.1
- git version (`git --version`): 2.3.5
